# Generated by Django 6.0.5 on 2026-05-27 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement & Fuel'), ('UTILITY_ELECTRICITY', 'Utility - Electricity'), ('TRAVEL_CORPORATE', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=50)),
                ('traveler_name', models.CharField(max_length=255)),
                ('travel_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel Night'), ('GROUND_TRANSPORT', 'Ground Transport (taxi, car rental, etc)')], max_length=20)),
                ('travel_date', models.DateField()),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Corporate Vehicles'), ('SCOPE_3', 'Scope 3 - Business Travel')], default='SCOPE_3', max_length=10)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.dataingestionlog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=50)),
                ('line_item', models.CharField(max_length=10)),
                ('plant_code', models.CharField(max_length=10)),
                ('material_code', models.CharField(max_length=50)),
                ('vendor_code', models.CharField(blank=True, max_length=20)),
                ('vendor_name', models.CharField(max_length=255)),
                ('quantity_original', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_original', models.CharField(max_length=10)),
                ('quantity_tonnes', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('procurement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], default='SCOPE_3', max_length=10)),
                ('emission_category', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.dataingestionlog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'procurement_date'], name='ingestion_p_organiz_0dde87_idx'), models.Index(fields=['organization', 'review_status'], name='ingestion_p_organiz_466f6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SAPPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=10)),
                ('plant_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'unique_together': {('organization', 'plant_code')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'unique_together': {('organization', 'supplier_code')},
            },
        ),
        migrations.CreateModel(
            name='UtilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_id', models.CharField(max_length=50)),
                ('facility_location', models.CharField(max_length=255)),
                ('reading_date', models.DateField()),
                ('consumption_kwh_original', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumption_kwh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('demand_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('tariff_name', models.CharField(blank=True, max_length=100)),
                ('rate_per_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.dataingestionlog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'reading_date'], name='ingestion_u_organiz_63b0db_idx'), models.Index(fields=['organization', 'review_status'], name='ingestion_u_organiz_e6c3a7_idx')],
            },
        ),
    ]
